

url: "https://kingcoatskennels.com" # the base hostname & protocol for your site, e.g. http://example.com

author: Dave M. Coats



#theme: jekyll-theme-midnight


exclude:
    - .gitignore
    - CNAME
